services:

  backend:
    image: namratha3/dd-mean-backend
    container_name: mean-backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017/mean_db
    ports:
      - "8083:8080"   
    networks:
      - mean-network

  frontend:
    image: namratha3/dd-mean-frontend
    container_name: mean-frontend
    networks:
      - mean-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - mean-network

  mongo:
    image: mongo:5
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - mean-network

networks:
  mean-network:

volumes:
  mongo_data:
  frontend_build: